### ISSUE TITLE
FEATURE: Sales Page - Suggested Price

### ISSUE THREAD

**Issue by demonlexe** [demonlexe/howrse-advisor#21]
Run a web scrape (background script) on horse's attributes to determine its worth in sales

(Notes for me: Similar to RMP scrape from skedge)

**Comment by demonlexe** [comment]
So, I'm thinking for this, the most important, general search terms will be;
- Genetic Potential
- Skills
- Species
- Is a unicorn, pegasus, both
- Any BMIs that it has

**Comment by demonlexe** [comment]
Then we can add special cases. 
- If Donkey/Draft, then use how many coverings it has left.
- If it has BLUP >= 60, include this in the search term aswell.

Thing I don't think matter that much:
- If it's pure-bred or not
- Specific skill levels
- Age
- Riding style

**Comment by CrimsonVex** [comment]
Before going to a sell page, my previous approaches have been to hold onto the horses stats in cache to avoid re-fetching, though I'm not sure if that's feasible to do in this case.
