### ISSUE TITLE
Some Settings don't work (Spanish Version)

### ISSUE THREAD

**Issue by CrazyUserJr** [demonlexe/howrse-advisor#50]
I have been using this script in the Spanish version of Howrse (caballow.com). I have changed the URLs in the manifest file, but I have encountered several errors. I'm not sure if I need to do any additional configuration. Here are the main errors I have had:

When enabling automatic feeding, it sets the forage correctly, but for some reason, it doubles the portion of oats.
The automatic purchase of EC does not work.
The automatic competitions do not work.

**Comment by demonlexe** [comment]
Hey! If you want to set up a time to chat (Not sure what your comfort level with english is) that would be great so you can show me what's going on!

As for the oats thing, that was intentional and experimental by me (I like the energy boost) but I should probably not have that on the main branch, or I should at least move it into a separate advanced panel

**Comment by CrazyUserJr** [comment]
Okay, I sent you a Discord Friend Request to chat there and try to fix this.

**Comment by demonlexe** [comment]
> Okay, I sent you a Discord Friend Request to chat there and try to fix this.

I didn't get anything-- Did you send it to lexi#9015

**Comment by CrazyUserJr** [comment]
> > Okay, I sent you a Discord Friend Request to chat there and try to fix this.
> 
> I didn't get anything-- Did you send it to lexi#9015

Yes, I did. My discord is: Gasu#4392

**Comment by demonlexe** [comment]
> 

I sent you a friend request! I will have time this weekend to work with you on this.

**Comment by demonlexe** [comment]
Pushed many changes to this on current main branch. Let me know if anything else is broken; There were a few things I was unable to test today because I had to make a new account.
